export const DEVICE_CSV_FIELDS = [
	"name",
	"description",
	"user",
	"status",
	"type",
	"location",
	"make-model",
	"serialnumber",
	"productnumber",
	"macaddress",
	"warrantystart",
	"warrantyend",
	"warrantytype",
	"cost",
	"os",
    "domain",
	"purchasedate",
	"endoflife",
	"expectedreplacementyear",
	"plandescription",
	"extranotes",
	"billedto",
	"costto",
	"supportsite",
	"driverslink",
	"warrantylink"
] as const
