import type { Metadata } from "next";
import { ThemeProvider } from "@/providers/theme-provider"
import { PreferencesLoader } from "@/providers/preferences-loader"
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Toaster } from "@/components/ui/sonner"

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "MCC BC Inventory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={`${roboto.variable} ${robotoMono.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <PreferencesLoader />
            <Header />
            <main className="mx-auto px-4 sm:px-6 lg:px-8 xl:px-24 py-6">
              {children}
            </main>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
  );
}
